### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by acarist** [kryptxy/torrench#16]
I get an error when I try piratebay. I think soup couldn't find the element.

`######################
#                    #
#    ThePirateBay    #
#                    #
######################

Obtaining proxies...
>>> Trying https://pirateproxy.cam
Fetching results...
Traceback (most recent call last):
  File "/usr/local/bin/torrench", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/torrench/__main__.py", line 8, in main
    args()
  File "/usr/local/lib/python3.6/site-packages/torrench/Torrench.py", line 26, in args
    main(args)
  File "/usr/local/lib/python3.6/site-packages/torrench/Torrench.py", line 87, in main
    torrent_fetch(args)
  File "/usr/local/lib/python3.6/site-packages/torrench/Torrench.py", line 55, in torrent_fetch
    tpb.main(input_title, page_limit)
  File "/usr/local/lib/python3.6/site-packages/torrench/modules/thepiratebay.py", line 294, in main
    output = get_results(url, title, page_limit)
  File "/usr/local/lib/python3.6/site-packages/torrench/modules/thepiratebay.py", line 114, in get_results
    output = fetch_results(soup)
  File "/usr/local/lib/python3.6/site-packages/torrench/modules/thepiratebay.py", line 141, in fetch_results
    website_url = soup.find('img', id='TPBlogo')['src'].split('/')[2]
TypeError: 'NoneType' object is not subscriptable`

**Comment by kryptxy** [comment]
I have been getting the same. Digging further, the proxies are not responding. Looking for a fix. I'll update when I find one.

**Comment by kryptxy** [comment]
**UPDATE** : TPB/KAT proxies seems to be down. That's the reason this error is occuring. I couldn't find any working proxy. Once proxies are up, it should work fine.

**Comment by kryptxy** [comment]
A temp. fix - https://github.com/kryptxy/torrench/issues/18

**Comment by kryptxy** [comment]
TPB proxies are back online. Should work! Closing.
