### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by rajenlyz** [kryptxy/torrench#17]
Hi, when I use torrench to search torrents, there is error occurred. The info is as follows:

```
➜  ~ torrench -t "Alien"

######################
#                    #
#    ThePirateBay    #
#                    #
######################

Obtaining proxies...
>>> Trying https://pirateproxy.cam
Fetching results...
Traceback (most recent call last):
  File "/usr/local/bin/torrench", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/torrench/__main__.py", line 8, in main
    args()
  File "/usr/local/lib/python3.5/dist-packages/torrench/Torrench.py", line 26, in args
    main(args)
  File "/usr/local/lib/python3.5/dist-packages/torrench/Torrench.py", line 87, in main
    torrent_fetch(args)
  File "/usr/local/lib/python3.5/dist-packages/torrench/Torrench.py", line 55, in torrent_fetch
    tpb.main(input_title, page_limit)
  File "/usr/local/lib/python3.5/dist-packages/torrench/modules/thepiratebay.py", line 294, in main
    output = get_results(url, title, page_limit)
  File "/usr/local/lib/python3.5/dist-packages/torrench/modules/thepiratebay.py", line 114, in get_results
    output = fetch_results(soup)
  File "/usr/local/lib/python3.5/dist-packages/torrench/modules/thepiratebay.py", line 141, in fetch_results
    website_url = soup.find('img', id='TPBlogo')['src'].split('/')[2]
TypeError: 'NoneType' object is not subscriptable

```

Could you help to give some suggestions for this issue? Thanks.

**Comment by rajenlyz** [comment]
This issue has been opened.
