### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by Jedipottsy** [kryptxy/torrench#20]
Hi,
under ubuntu 16.04 i get the following error

```
[The Pirate Bay]

Obtaining proxies...
Traceback (most recent call last):
  File "/usr/local/bin/torrench", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/torrench/__main__.py", line 31, in main
    Torrench.main()
  File "/usr/local/lib/python3.5/dist-packages/torrench/Torrench.py", line 194, in main
    tr.resolve_args()
  File "/usr/local/lib/python3.5/dist-packages/torrench/Torrench.py", line 150, in resolve_args
    tpb.main(self.input_title, self.page_limit)
  File "/usr/local/lib/python3.5/dist-packages/torrench/modules/thepiratebay.py", line 316, in main
    tpb = ThePirateBay(title, page_limit)
  File "/usr/local/lib/python3.5/dist-packages/torrench/modules/thepiratebay.py", line 29, in __init__
    self.proxies = self.get_proxies('tpb')
  File "/usr/local/lib/python3.5/dist-packages/torrench/utilities/Config.py", line 66, in get_proxies
    link = soup.find_all('td', class_='site')
AttributeError: 'int' object has no attribute 'find_all'

```

**Comment by kryptxy** [comment]
Please attach the log file [```~/.local/share/torrench/```]

**Comment by kosmonautbruce** [comment]
I installed and then ran the example search, and got the exact error reported here. Attached is my log file. Thanks.
[torrench (copy).txt](https://github.com/kryptxy/torrench/files/1297120/torrench.copy.txt)

**Comment by kryptxy** [comment]
Try the following: 

```python3 -m pip install certifi```

**Comment by kryptxy** [comment]
Great!
@Jedipottsy The same should work for you too. In case it doesn't feel free to comment. Do attach the log file.
(Closing!)
