### ISSUE TITLE
NoneType exception (related to BeautifulSoup ?) 

### ISSUE THREAD

**Issue by stephanepiriou** [kryptxy/torrench#72]
Here the command + output

```bash
macbook:~ stephane$ torrench-all test

[Cross-Site Search]


[THEPIRATEBAY]

Obtaining proxies...
Trying https://thepiratebay.org
Proxy available. Performing test...
Pass!

Fetching from page: 1
[in 0.77 sec]
(no results)

[KICKASSTORRENT]

Obtaining proxies...
Trying https://kickass.cd/
Bad proxy!
Trying https://kickass.unblocked.bid/
Bad proxy!
Trying https://kickass.unlockproj.faith/
Traceback (most recent call last):
  File "/usr/local/bin/torrench", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/torrench/__main__.py", line 28, in main
    Torrench.main()
  File "/usr/local/lib/python3.6/site-packages/torrench/Torrench.py", line 326, in main
    cs.main(tr.args)
  File "/usr/local/lib/python3.6/site-packages/torrench/utilities/cross_site.py", line 276, in main
    cs.stage_one(arguments)
  File "/usr/local/lib/python3.6/site-packages/torrench/utilities/cross_site.py", line 65, in stage_one
    module_obj.check_proxy()
  File "/usr/local/lib/python3.6/site-packages/torrench/modules/kickasstorrent.py", line 67, in check_proxy
    if self.soup.find('a')['href'] != proxy + "/full/" or self.soup == -1:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by datafanatic** [comment]
This generally happens when the website is offline. I have just tested and kickass.cd is currently up. Would you please try again?

**Comment by stephanepiriou** [comment]
There is 2 issues here :
>`kickass.cd` ==> I can ping or access from my browser, but it refuse access the server (Bad Proxy). Exception, if occuring, is handled : Torrench try the next address...

>`kickass.unlockproj.faith` ==> It so filled with ads that I'm redirected to a dirty private webcam site from my browser... And torrench doesn't handle the exception raise and stop abruptly...

**Comment by stephanepiriou** [comment]
It seems they protected the search input field with some magic trick on kickass.cd. I can't edit the html inner code of the input from the code inspector in safari, but still can delete or edit the input tag itself.
![Search Field](https://user-images.githubusercontent.com/20599429/36390266-c821dada-15a2-11e8-9f7e-c7ec337c4432.jpg)
