### ISSUE TITLE
AttributeError: 'int' object has no attribute 'find_all' on torrench -Ctisx 'ubuntu'

### ISSUE THREAD

**Issue by chetnuy** [kryptxy/torrench#78]
`$ torrench -Ctisx 'ubuntu'`
`[Cross-Site Search]

[THEPIRATEBAY]

Obtaining proxies...
Traceback (most recent call last):
  File "/usr/bin/torrench", line 11, in <module>
    load_entry_point('torrench==1.0.61', 'console_scripts', 'torrench')()
  File "/usr/lib/python3.6/site-packages/torrench/__main__.py", line 28, in main
    Torrench.main()
  File "/usr/lib/python3.6/site-packages/torrench/Torrench.py", line 326, in main
    cs.main(tr.args)
  File "/usr/lib/python3.6/site-packages/torrench/utilities/cross_site.py", line 276, in main
    cs.stage_one(arguments)
  File "/usr/lib/python3.6/site-packages/torrench/utilities/cross_site.py", line 58, in stage_one
    module_obj = module.cross_site(self.title, self.pages)
  File "/usr/lib/python3.6/site-packages/torrench/modules/thepiratebay.py", line 237, in cross_site
    tpb = ThePirateBay(title, page_limit)
  File "/usr/lib/python3.6/site-packages/torrench/modules/thepiratebay.py", line 27, in __init__
    self.proxies = self.get_proxies('tpb')
  File "/usr/lib/python3.6/site-packages/torrench/utilities/Config.py", line 93, in get_proxies
    link = soup.find_all('td', class_='site')
AttributeError: 'int' object has no attribute 'find_all'
`

**Comment by datafanatic** [comment]
Hi chetnuy, could you please provide the logs? You can find them (assuming you're in Linux or MacOS) in `~/.local/share/torrench` and `%AppData%\Local\torrench` in Windows.

**Comment by DimaBroi** [comment]
It seems to be happening for https://www.skytorrents.in also.
I tried : 
torrench-1.0.61.exe -s 'ubuntu'

and got : 
[SkyTorrents]

Obtaining proxies...
Trying https://www.skytorrents.in
Error message: 'int' object has no attribute 'find_all'
Something went wrong! See logs for details. Exiting!

**Comment by RafayGhafoor** [comment]
@DimaBroi & @kryptxy, [Skytorrents is dead](https://torrentfreak.com/skytorrents-dumps-massive-torrent-database-and-shuts-down180221/)
