### ISSUE TITLE
Rarbg does not work

### ISSUE THREAD

**Issue by antoyo** [kryptxy/torrench#82]
Hi.
When I do a search with `--rarbg`, it shows the following error:
```
Traceback (most recent call last):
  File "/usr/bin/torrench", line 11, in <module>
    load_entry_point('torrench==1.0.61', 'console_scripts', 'torrench')()
  File "/usr/lib/python3.6/site-packages/torrench/__main__.py", line 28, in main
    Torrench.main()
  File "/usr/lib/python3.6/site-packages/torrench/Torrench.py", line 340, in main
    tr.resolve_args()
  File "/usr/lib/python3.6/site-packages/torrench/Torrench.py", line 277, in resolve_args
    rbg.main(self.input_title)
  File "/usr/lib/python3.6/site-packages/torrench/modules/rarbg.py", line 99, in main
    rbg.get_token()
  File "/usr/lib/python3.6/site-packages/torrench/modules/rarbg.py", line 45, in get_token
    raw = requests.get(self.proxy+get_token).json()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Thanks to fix the issue.

**Comment by kryptxy** [comment]
This was fixed some time back. Please re-build from source.

https://github.com/kryptxy/torrench/commit/2c4869ebc48012531689830351159da7b3f104b5

**Comment by antoyo** [comment]
Thanks.
