### ISSUE TITLE
rarbg failed

### ISSUE THREAD

**Issue by fratcn** [kryptxy/torrench#87]
[RarBg]

Traceback (most recent call last):
  File "/usr/bin/torrench", line 11, in <module>
    load_entry_point('torrench==1.0.61', 'console_scripts', 'torrench')()
  File "/usr/lib/python3.7/site-packages/torrench/__main__.py", line 28, in main
    Torrench.main()
  File "/usr/lib/python3.7/site-packages/torrench/Torrench.py", line 340, in main
    tr.resolve_args()
  File "/usr/lib/python3.7/site-packages/torrench/Torrench.py", line 277, in resolve_args
    rbg.main(self.input_title)
  File "/usr/lib/python3.7/site-packages/torrench/modules/rarbg.py", line 99, in main
    rbg.get_token()
  File "/usr/lib/python3.7/site-packages/torrench/modules/rarbg.py", line 45, in get_token
    raw = requests.get(self.proxy+get_token).json()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

**Comment by kryptxy** [comment]
Working on my end. Rarbg uses API to fetch results. Please make sure you are building from source. A patch was provided long time back, but was not released through pip. Please build from source and try again.

**Comment by Frydac** [comment]
FYI: the arch package is also too old. 
After building from source at rarbg worked.
